### ISSUE TITLE
this is a request for help :(  uploading an output template to dsw server

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/dsw-tdk#21]
Hello all,

I did post this in the slack (Yvonne Kallberg gives me a way out), but still, it would be nice if I could figure out what to do :( :
 
* I created a new output template: it is sitting  on my computer and I need to import it into our DSW standalone site (template was developed thanks to a local DSW install)
* how to I do this? ie. which files should I import given a template is made of several files?
* the reason I ask this question is I can't or don't know how to push the template via dsw-tdk put: obviously the API is not configured properly....  but I don't know how to proceed...

the log file shows:
dsw_server    | 2021-03-30T14:44:42.195967259Z [Warn ] [I:------------------------------------] [T:------------------------------------] [API         ] 401 Unauthorized POST /tokens

so it is a token problem

Btw, if I install dsw-tdk (yes, with the matching version) on the DSW server, and try to push it through localhost:3000 I get the same error:
dsw_server    | 2021-03-31T08:28:43.171207192Z [Warn ] [I:------------------------------------] [T:------------------------------------] [API         ] 401 Unauthorized POST /tokens

So it is a token problem?

Sorry for this stupid question but any help would be appreciated; unless it is a bug????  (being confused)
Many thanks.

**Comment by MarekSuchanek** [comment]
Hi Paulette, it seems like you have a bad credentials.. Do you have `.env` file or how do you provide credentials to `dsw-tdk`?

**Comment by froggypaule** [comment]
Hello Marek. Yes to all your questions. Just to make sure, I did change (again) my credentials to (re) check. Same issue, same log warnings. Did it from same machine and from a different server.
Am on holidays currently, so might not answer very rapidly.
Maybe we shouldn't bother too much: I am in the process of installing the prod DSW with the 2.12.0 version, so this might solve the issue altogether. Thanks.

**Comment by froggypaule** [comment]
hello @marek: as expected, this was a stupid error of mine.... :(
