### ISSUE TITLE
dsw-tdk for 2.13?

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/dsw-tdk#23]
Hello!
I just realised that there is no 2.13 image (yet) for dsw-tdk. So I used dsw-tdk 2.12 to push templates on the new 2.13 image. It worked without issues; but since it is advertised that we should always use the matching versions...
Cheers.

**Comment by MarekSuchanek** [comment]
Hello, indeed it took a while... I needed to fix one minor issue before the release. Now `v2.13.0` is available.
