### ISSUE TITLE
dsw-tdk for 3.2.0?

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/dsw-tdk#36]
Hello @MarekSuchanek : it looks like dsw-tdk doesn't yet handle the metamodelVersion 4 at this stage:

INFO: Loading local template project
INFO: Connecting to https://dsws.france-bioinformatique.fr
INFO: Successfully authenticated as paulette.lieby@france-bioinformatique.fr
FAILURE: Could not upload template
> Unknown metamodel version: 4
> Fix your metamodelVersion in template.json and/or visit docs

Since dsw-tdk is still given as v 3.2.1... thanks!

**Comment by MarekSuchanek** [comment]
Hi @froggypaule, that is strange as we (me and Jan) were developing templates with TDK and metamodel v4 this sprint without issues... Is the `metamodelVersion ` in your `template.json`  set to `4` (number not string)?

```json
{ "metamodelVersion": 4 }
```

**Comment by froggypaule** [comment]
this is what I have:

  "metamodelVersion": 4,

simply changing 3 to 4...

**Comment by froggypaule** [comment]
you may want to test it:
[ifb_generic_template.zip](https://github.com/ds-wizard/dsw-tdk/files/7090890/ifb_generic_template.zip)

**Comment by MarekSuchanek** [comment]
And what exactly is shown by `dsw-tdk --version`?

**Comment by froggypaule** [comment]
Indeed: "dsw-tdk, version 2.14.0"
I though I had the latest! --will get back to you.

**Comment by froggypaule** [comment]
Ok, of course, this is the answer. Thanks!
